import { createHash } from "node:crypto";
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, isAbsolute, join, relative, resolve } from "node:path";
import type { CompetitionConfig, ExperimentManifest, RunResult } from "./types.js";

export interface SubmissionValidation {
  valid: boolean;
  bundlePath: string;
  checks: Array<{ name: string; passed: boolean; detail: string }>;
}

function checksum(path: string): string {
  return `sha256:${createHash("sha256").update(readFileSync(path)).digest("hex")}`;
}

export function prepareSubmission(root: string, experimentId: string, manifest: ExperimentManifest, run: RunResult, competition: CompetitionConfig): { id: string; path: string } {
  if (run.status !== "completed" || run.exitCode !== 0) throw new Error(`Cannot prepare a submission from run ${run.runId}: run is not successfully completed.`);
  const id = `sub_${Date.now()}_${experimentId}`;
  const path = join(root, ".sota", "submissions", id);
  mkdirSync(path, { recursive: true });
  const copied: string[] = [];
  for (const [name, artifactPath] of Object.entries(run.artifacts)) {
    if (!existsSync(artifactPath)) continue;
    if (!/submission|prediction/i.test(name)) continue;
    const destination = join(path, basename(artifactPath));
    copyFileSync(artifactPath, destination);
    copied.push(destination);
  }
  const submission = competition.submission ?? { platform: "manual", source: "prediction" };
  if (!copied.length && submission.source !== "workspace") throw new Error(`Run ${run.runId} has no submission or prediction artifact.`);
  const provenance = { schemaVersion: 1, submissionId: id, experimentId, competition: competition.id, submission, manifest, run: { runId: run.runId, status: run.status, metrics: run.metrics, artifacts: run.artifacts }, createdAt: new Date().toISOString() };
  writeFileSync(join(path, "provenance.json"), `${JSON.stringify(provenance, null, 2)}\n`);
  writeFileSync(join(path, "model_card.md"), `# ${id}\n\nCompetition: ${competition.name}\nExperiment: ${experimentId}\nRun: ${run.runId}\n\nThis bundle was generated by Evidra. External submission remains approval-gated.\n`);
  writeFileSync(join(path, "UPLOAD_INSTRUCTIONS.md"), `# Manual upload\n\nValidate this bundle with Evidra before uploading. Do not provide credentials to research agents.\n\nPrediction artifacts copied: ${copied.length}\n`);
  const checksums = ["provenance.json", "model_card.md", "UPLOAD_INSTRUCTIONS.md", ...copied.map((file) => file.split(/[\\/]/).pop() ?? file)].map((name) => `${checksum(join(path, name))}  ${name}`).join("\n");
  writeFileSync(join(path, "checksums.sha256"), `${checksums}\n`);
  return { id, path };
}

export function validateSubmissionBundle(path: string): SubmissionValidation {
  const checks: SubmissionValidation["checks"] = [];
  const provenancePath = join(path, "provenance.json");
  const checksumPath = join(path, "checksums.sha256");
  checks.push({ name: "provenance", passed: existsSync(provenancePath), detail: existsSync(provenancePath) ? "provenance.json exists" : "provenance.json is missing" });
  checks.push({ name: "checksums", passed: existsSync(checksumPath), detail: existsSync(checksumPath) ? "checksums.sha256 exists" : "checksums.sha256 is missing" });
  let provenance: { submissionId?: unknown; experimentId?: unknown; submission?: { source?: unknown } } | undefined;
  if (existsSync(provenancePath)) {
    try { provenance = JSON.parse(readFileSync(provenancePath, "utf8")) as { submissionId?: unknown; experimentId?: unknown }; }
    catch { /* reported as a failed provenance check below */ }
  }
  checks.push({ name: "provenance-schema", passed: typeof provenance?.submissionId === "string" && typeof provenance?.experimentId === "string", detail: typeof provenance?.submissionId === "string" && typeof provenance?.experimentId === "string" ? "submission and experiment identifiers exist" : "provenance.json is invalid or incomplete" });
  let predictionArtifact = false;
  if (existsSync(checksumPath)) {
    for (const line of readFileSync(checksumPath, "utf8").split("\n").map((value) => value.trim()).filter(Boolean)) {
      const separator = line.indexOf("  ");
      if (separator <= 0) { checks.push({ name: "checksum:format", passed: false, detail: "expected '<sha256>  <filename>'" }); continue; }
      const expected = line.slice(0, separator);
      const name = line.slice(separator + 2);
      const file = join(path, name);
      const fileRelative = relative(resolve(path), resolve(file));
      const safeName = !isAbsolute(fileRelative) && !fileRelative.startsWith("..");
      const passed = safeName && existsSync(file) && checksum(file) === expected;
      if (safeName && /submission|prediction/i.test(name) && existsSync(file)) predictionArtifact = true;
      checks.push({ name: `checksum:${name}`, passed, detail: passed ? "matches" : "missing or changed" });
    }
  }
  const workspaceSource = provenance?.submission?.source === "workspace";
  checks.push({ name: "prediction-artifact", passed: predictionArtifact || workspaceSource, detail: predictionArtifact ? "submission or prediction artifact is present" : workspaceSource ? "workspace-source adapter will submit from the configured working directory" : "no submission or prediction artifact is present" });
  return { valid: checks.every((check) => check.passed), bundlePath: path, checks };
}
