import { createHash } from "node:crypto";
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { CompetitionConfig, ExperimentManifest, RunResult } from "./types.js";

export interface SubmissionValidation {
  valid: boolean;
  bundlePath: string;
  checks: Array<{ name: string; passed: boolean; detail: string }>;
}

function checksum(path: string): string {
  return `sha256:${createHash("sha256").update(readFileSync(path)).digest("hex")}`;
}

export function prepareSubmission(root: string, experimentId: string, manifest: ExperimentManifest, run: RunResult, competition: CompetitionConfig): { id: string; path: string } {
  const id = `sub_${Date.now()}_${experimentId}`;
  const path = join(root, ".sota", "submissions", id);
  mkdirSync(path, { recursive: true });
  const copied: string[] = [];
  for (const [name, artifactPath] of Object.entries(run.artifacts)) {
    if (!existsSync(artifactPath)) continue;
    if (!/submission|prediction/i.test(name)) continue;
    const destination = join(path, name.split(/[\\/]/).pop() ?? name);
    copyFileSync(artifactPath, destination);
    copied.push(destination);
  }
  const provenance = { schemaVersion: 1, submissionId: id, experimentId, competition: competition.id, manifest, run: { runId: run.runId, status: run.status, metrics: run.metrics, artifacts: run.artifacts }, createdAt: new Date().toISOString() };
  writeFileSync(join(path, "provenance.json"), `${JSON.stringify(provenance, null, 2)}\n`);
  writeFileSync(join(path, "model_card.md"), `# ${id}\n\nCompetition: ${competition.name}\nExperiment: ${experimentId}\nRun: ${run.runId}\n\nThis bundle was generated by Evidra. External submission remains approval-gated.\n`);
  writeFileSync(join(path, "UPLOAD_INSTRUCTIONS.md"), `# Manual upload\n\nValidate this bundle with Evidra before uploading. Do not provide credentials to research agents.\n\nPrediction artifacts copied: ${copied.length}\n`);
  const checksums = ["provenance.json", "model_card.md", "UPLOAD_INSTRUCTIONS.md", ...copied.map((file) => file.split(/[\\/]/).pop() ?? file)].map((name) => `${checksum(join(path, name))}  ${name}`).join("\n");
  writeFileSync(join(path, "checksums.sha256"), `${checksums}\n`);
  return { id, path };
}

export function validateSubmissionBundle(path: string): SubmissionValidation {
  const checks: SubmissionValidation["checks"] = [];
  const provenancePath = join(path, "provenance.json");
  const checksumPath = join(path, "checksums.sha256");
  checks.push({ name: "provenance", passed: existsSync(provenancePath), detail: existsSync(provenancePath) ? "provenance.json exists" : "provenance.json is missing" });
  checks.push({ name: "checksums", passed: existsSync(checksumPath), detail: existsSync(checksumPath) ? "checksums.sha256 exists" : "checksums.sha256 is missing" });
  if (existsSync(checksumPath)) {
    for (const line of readFileSync(checksumPath, "utf8").split("\n").map((value) => value.trim()).filter(Boolean)) {
      const separator = line.indexOf("  ");
      const expected = line.slice(0, separator);
      const name = line.slice(separator + 2);
      const file = join(path, name);
      const passed = existsSync(file) && checksum(file) === expected;
      checks.push({ name: `checksum:${name}`, passed, detail: passed ? "matches" : "missing or changed" });
    }
  }
  return { valid: checks.every((check) => check.passed), bundlePath: path, checks };
}
